### ISSUE TITLE
`Namespace` object has no attribute `lora_dir`

### ISSUE THREAD

**Issue by cppietime** [civitai/sd_civitai_extension#11]
Tried installing into SD Webui using the install from repo URL option, then when restarting it, the below was reported:

```
Exception in thread Thread-48 (load_previews):
Traceback (most recent call last):
  File "C:\Users\alpac\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\alpac\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\sd_civitai_extension\scripts\previews.py", line 15, in load_previews
    resources = civitai.load_resource_list()
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\sd_civitai_extension\civitai\lib.py", line 189, in load_resource_list
    resources += get_resources_in_folder('LORA', shared.cmd_opts.lora_dir, ['pt', 'safetensors', 'ckpt'])
AttributeError: 'Namespace' object has no attribute 'lora_dir'
```

I am running in an anacaonda env

**Comment by JustMaier** [comment]
What version of Automatic1111 are you running?
At the bottom of your screen you should see something like this:
![image](https://user-images.githubusercontent.com/607609/221878471-299864fe-d7e8-43ea-be2e-cc5061ee5a07.png)
