### ISSUE TITLE
ERROR: Cannot install launch==0.1.0, launch==0.1.1, launch==0.1.2 and launch==0.1.3 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by akinLiu** [civitai/sd_civitai_extension#23]
1. `python install.py`

`Traceback (most recent call last):
  File "/root/soft/sd_civitai_extension/install.py", line 7, in <module>
    from launch import run
ModuleNotFoundError: No module named 'launch'`

2. `pip install launch`

```
(py310) root@ubuntu20:~/soft/sd_civitai_extension# python install.py
Traceback (most recent call last):
  File "/root/soft/sd_civitai_extension/install.py", line 7, in <module>
    from launch import run
ModuleNotFoundError: No module named 'launch'
(py310) root@ubuntu20:~/soft/sd_civitai_extension# pip install launch
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting launch
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/a9/c1/793768c803a25e2e101ed88fe3979f17d4d67d160aedb3c3bd143653f068/launch-0.1.3.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/4a/cd/ba5ade0b40ce222d49d25aa22c6741e5de4a3ce89a5d7db507c749144137/launch-0.1.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/02/ea/f08cc7605f62868c5bc8ba7d64a7292ea58739696f0d8016a264daeca186/launch-0.1.1.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/b0/ef/1b1bca20ef3a088dd6475d9733ef58fcc4db2ab34a19003063d931dc9a28/launch-0.1.0.tar.gz (7.2 kB)
  Preparing metadata (setup.py) ... done
ERROR: Cannot install launch==0.1.0, launch==0.1.1, launch==0.1.2 and launch==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    launch 0.1.3 depends on flowdas-meta<1.1 and >=1.0.1
    launch 0.1.2 depends on flowdas-meta<1.1 and >=1.0.1
    launch 0.1.1 depends on flowdas-meta<1.1 and >=1.0.1
    launch 0.1.0 depends on flowdas-meta<1.1 and >=1.0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
3. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

system info:
ubuntu 20.04
python 3.10
pip 22.3.1

**Comment by azodev** [comment]
same here

**Comment by arditobryan** [comment]
hi, i have the same problem
Additionally, requirements.txt does not have the PythonGit library which is necessary to run install.py

**Comment by Skysliao** [comment]
same here

**Comment by SpacePiggy17** [comment]
Same issue here.

**Comment by jiyuren** [comment]
modify you install.py insert sys.path.append('../YOUR_PATH') the launch module is your launch.py  just import it

**Comment by fsandovalz** [comment]
Same issue :(

**Comment by jtac** [comment]
> modify you install.py insert sys.path.append('../YOUR_PATH') the launch module is your launch.py just import it

can you please explain your answer? adding this ( even using insert(0, doesn't seem to help me

**Comment by LanHao0** [comment]
> > modify you install.py insert sys.path.append('../YOUR_PATH') the launch module is your launch.py just import it
> 
> can you please explain your answer? adding this ( even using insert(0, doesn't seem to help me

![image](https://user-images.githubusercontent.com/14994590/236216341-76d15384-471b-4758-8678-20f14fee05cf.png)
add it to here, I guess the launch means launch.py in the folder.

**Comment by SpacePiggy17** [comment]
> Can someone properly explain how to fix it **in English** or make a pull request?

Python is failing to import a module. Usually, this can be solved by running "pip install <package>" inside of the terminal but because "launch" is not a package defined in the pip repository, we cannot use pip for this. Instead, we need to specify a path where Python looks for the "launch" module. "launch.py" is a Python script in the webui and is what we need to import. So instead of finding and installing something on the internet using pip, the webui uses a file path on your computer to import the "launch.py" script.

To fix this we need to change where python is looking. Normally we would have to use pip to install a module from the internet using pip, but we want it to look on our computer. To do that simply in a Python program, we can import the "sys" package (which is defined by Python) and add a file path to where it is looking to import from. Go to the extensions folder, find this extension's folder, open the "launch.py" file (for the extension), and add this code to the top:

import sys
sys.append("your/file/path/to/a1111/here") #MAKE SURE YOU CHANGE THE FILE PATH BEFORE YOU IMPORT "LAUNCH"

Now, when the script does "from launch import run" later on, it will check the webui folder and try importing the module from there.

What "sys.append()" does, is take an input of the file path you want to add: set this to your "stable-diffusion-webui" folder (for a1111) path. Mine on Linux looks like "sys.append("/home/myname/stable-diffusion-webui")". Then after we have added the file path to a list that it checks when importing, we can import the "launch" module as done by the line later on: "from launch import run".

I find myself having to do this pretty often with new extensions if they fail to import "launch". I just go into the script and change the file path to include the a1111 webui folder and it usually works. Hope this helped. I am still learning too.

**Comment by adoontheway** [comment]
![11111](https://github.com/civitai/sd_civitai_extension/assets/1528180/5ccc62f5-cb8d-4634-b75a-730868cde11e)

> import sys
sys.append("your/file/path/to/a1111/here") #MAKE SURE YOU CHANGE THE FILE PATH BEFORE YOU IMPORT "LAUNCH"

works for me

**Comment by ifiddle** [comment]
> ![11111](https://user-images.githubusercontent.com/1528180/243084378-5ccc62f5-cb8d-4634-b75a-730868cde11e.png)
> 
> > import sys
> > sys.append("your/file/path/to/a1111/here") #MAKE SURE YOU CHANGE THE FILE PATH BEFORE YOU IMPORT "LAUNCH"
> 
> works for me

its work, thanks!

**Comment by idiotcommerce** [comment]
nothing work for me. but this may be helpful
https://stackoverflow.com/questions/71009659/message-note-this-error-originates-from-a-subprocess-and-is-likely-not-a-prob

**Comment by bruce2233** [comment]
cd to your sd webui root path, run this command:
```bash
PYTHONPATH=$(pwd) python extensions/sd-webui-segment-anything/install.py
```

**Comment by ylfrs** [comment]
I'm having a similar issue with [batchlinks-webui](https://github.com/camenduru/batchlinks-webui), but It's much more complicated because I am trying to create a Docker image based on a modified version of [this repository.](https://github.com/ashleykleynhans/stable-diffusion-docker). I can't reference sd webui's launch.py on my local machine, because it wouldn't mean anything to the docker image.

**Comment by Jammers33** [comment]
if the above solution isn't working for you...Windows 
I like you was having many issues with 'pip install launch' and getting a reporting error of
 "ERROR: Cannot install launch==0.1.0, launch==0.1.1, launch==0.1.2 and launch==0.1.3 
because these package versions have conflicting dependencies. The conflict is caused by: 
launch 0.1.3 depending on , 
flowdas-meta\<1.1 and \>=1.0.1 
launch 0.1.2 depends on 
flowdas-meta\<1.1 and \>=1.0.1
 launch 0.1.1 depends on
 flowdas-meta\<1.1 and \>=1.0.1
 launch 0.1.0 depends on
 flowdas-meta\<1.1 and \>=1.0.1\
 To fix this you could try to: 1. loosen the range of package versions you've specified 2. remove package versions to allow pip attempt to solve the dependen
 I went ahead and downloaded the Downloading launch-0.1.3.tar.gz (10 kB) Downloading launch-0.1.2.tar.gz (10 kB) Downloading launch-0.1.1.tar.gz (10 kB) Downloading launch-0.1.0.tar.gz (7.2 kB) that the call was asking for, upon examination of the setup.py in the folder 'launch-0.1.3' the first line of 'install_requires' had the call to download flowdas to a defunct https://bitbucket.org/flowdas/launch, it simply is nonexistent and there are a lot of people that can't download it, but still need it. 
I went ahead and emailed the author. After all that I went and updated my flowdas to 0.5.0 https://pypi.org/project/flowdas/
 'pip install flowdas' 
installed it then I went back to setup.py and changed the first three lines to update to
install_requires = [
    'flowdas>=0.5.0,<0.6.0',
    'click>=6.7,<6.8',
    'PyYAML>=3.12,<3.13',
, to reflect all the new updated versions to be installed that includes all three lines, in the root folder of launch-0.1.3 I executed the
 pip install -e .
 , and wouldn't you know it installed, all of it...
Now I am not responsible for what happens if anything to your machine, as this works for me and my application and it may not work for you, best to do everything you can in a VENV. Hope that helps! bingo, bongo, bango, you're the rock star, get after it!

**Comment by marketingstarz** [comment]
> ![11111](https://user-images.githubusercontent.com/1528180/243084378-5ccc62f5-cb8d-4634-b75a-730868cde11e.png)
> 
> > import sys
> > sys.append("your/file/path/to/a1111/here") #MAKE SURE YOU CHANGE THE FILE PATH BEFORE YOU IMPORT "LAUNCH"
> 
> works for me

Thanks for this. This helped me out!

**Comment by hypiuser** [comment]
```powershell
pip install --upgrade setuptools
``` 
solved my problem.

**Comment by Consulting4J** [comment]
add one line before "from lauch import run"
# your stable-diffusion-webui repo
sys.path.append('/home/rrrr/stable-diffusion-webui')
