### ISSUE TITLE
Not working with the Last Ben´s Colab

### ISSUE THREAD

**Issue by elBlacksmith** [civitai/sd_civitai_extension#38]
Hi,

It has happened to me a couple of times that after installing it successfully and downloading some files, it stops working if I execute TLB´s Colab.

This is the log code when running the last cell of TLB. Automatic1111 starts, but the link doesn´t longer work, and even on the settings of A1111 the CivitAI´s option is gone. But the icon on the top right is still there.

The only fix is to reinstall the extension, but it will gone again the next time.

```
Civitai: API loaded
Error loading script: link.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/scripts/link.py", line 3, in <module>
    import civitai.link as link
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/civitai/link.py", line 4, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'

Error loading script: settings.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/scripts/settings.py", line 1, in <module>
    from civitai.link import on_civitai_link_key_changed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/civitai/link.py", line 4, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'
```

**Comment by HorrySheet** [comment]
I seem to be unable to have the CivitAI tab show up in my automatic 1111 gui although it says it's installed in the list of extensions and the CivitAI logo is in the top right corner for me also.   Im not sure what went wrong but I dont have any errors like that showing in the colab console.

**Comment by elBlacksmith** [comment]
Hi,

the problem still exists. I updated the latest version of Automatic1111, I reinstalled the extension but after a restart of the system is gone the tab in the settings, making impossible to reconnect.
