### ISSUE TITLE
Startup warning: python-socketio[client] version 5.7.2 NOT installed.

### ISSUE THREAD

**Issue by mw88-personal** [civitai/sd_civitai_extension#42]
I have a newer version of ``python-socketio[client]`` in my venv, which does not get detected properly by the requirements.txt.

Please change ``requirements.txt`` to
~~~text
python-socketio[client]>=5.7.2
~~~
to include newer versions.

**Comment by YuFengDing** [comment]
same with you

**Comment by sumic** [comment]
pip install "python-socketio[client]"

**Comment by toniedeng** [comment]
first download: pip.py from web
second input: python get-pip.py
third input:  pip install "python-socketio[client]"
good lucky, ok!

**Comment by Recle** [comment]
首先，卸载掉高版本的python-socketio，在stable-diffusion-webui\【你的项目】\Scripts下，访问CMD，输入`pip list`查看是否有高版本的python-socketio，如果有，则输入`pip uninstall python-socketio`卸载。
卸载后，或者此前并没有python-socketio，输入`pip install python-socketio[client]==5.7.2`用来安装5.7.2这个特定版本

**Comment by bruce-yan** [comment]
I encountered the same problem, my machine has a python environment of 3.10.8. And installed python-socketio[client]==5.7.2.

##############################################################################################

Initializing Civitai Link

If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

Civitai Link revision: d0e83e7b048f9a6472b4964fa530f8da754aba58

SD-WebUI revision: 22bcc7be428c94e9408f589966c2040187245d81

Checking Civitai Link requirements...

[!] python-socketio[client] version 5.7.2 NOT installed.

##############################################################################################

**Comment by JimWatL** [comment]
> pip install python-socketio[client]==5.7.2

I have the same problem have you solved yours

**Comment by DarksealStudios** [comment]
Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

**Comment by JimWatL** [comment]
After hours of searching I'm going to bed, I hope to see more clearly tomorrow:(

**Comment by mw88-personal** [comment]
Just to clarify: I got the civitai extension working by changing the file ``<my base directory>\stable-diffusion-webui\extensions\sd_civitai_extension\requirements.txt``
from
~~~
python-socketio[client]==5.7.2
~~~
to 
~~~
python-socketio[client]>=5.7.2
~~~
locally. I have not experienced any bugs with the newer version, so I am staying on the version I am right now. This issues was raised as a feature request to incorporate my local change into future development for this extension, as I see no benefit in locking down the ``python-socketion[client]`` module to this exact version.

**Comment by DarksealStudios** [comment]
I added the requirements, and even though it got the extension working it would still say not installed. It wasn't until I ran cmd in the root folder of automatic1111 and entered :  pip install python-socketio==5.7.2   that it started working. Thanks everyone.... it's the wrong version of the extension, i needed the other one, lol! This one does't download images, it's the other one. Anyway, thank you for teaching me, [client] needed to be replaced with the version number. Slow, but learning.

**Comment by JimWatL** [comment]
> pip install python-socketio[client]==5.7.2

Can you explain us how you arrived there please I tried to put the zip and even the folder, 
here C:\Users\xxxxx\Documents\A1111 Web UI Autoinstaller 
and here C:\Users\jimmy\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui, t
hen to launch CMD since these same folder and made the installation but that always does not function :(

**Comment by hughlv** [comment]
> Just to clarify: I got the civitai extension working by changing the file `<my base directory>\stable-diffusion-webui\extensions\sd_civitai_extension\requirements.txt` from
> 
> ```
> python-socketio[client]==5.7.2
> ```
> 
> to
> 
> ```
> python-socketio[client]>=5.7.2
> ```
> 
> locally (Notice `>=` instead of `==`!). I have not experienced any bugs with the newer version, so I am staying on the version I am right now. This issues was raised as a feature request to incorporate my local change into future development for this extension, as I see no benefit in locking down the `python-socketion[client]` module to this exact version.

Thanks and this did eliminate the python-socketio[client] missing error, however, the following exception still exists:

```
Error executing callback app_started_callback for D:\ts\stable-diffusion-webui\extensions\sd_civitai_extension\scripts\link.py
Traceback (most recent call last):
  File "D:\ts\stable-diffusion-webui\modules\script_callbacks.py", line 108, in app_started_callback
    c.callback(demo, app)
  File "D:\ts\stable-diffusion-webui\extensions\sd_civitai_extension\scripts\link.py", line 13, in connect_to_civitai
    link.socketio_connect()
  File "D:\ts\stable-diffusion-webui\extensions\sd_civitai_extension\civitai\link.py", line 201, in socketio_connect
    sio.connect(socketio_url, socketio_path='/api/socketio')
  File "D:\ts\stable-diffusion-webui\venv\lib\site-packages\socketio\client.py", line 347, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
```

After restarting .\webui.bat , I still did not see the Civitai tab. Any ideas to fix this issue?

**Comment by freyandere** [comment]
Done, re-installing to 5.7.2 and restarting did the trick -xformers are loading and version check passed
![image](https://github.com/civitai/sd_civitai_extension/assets/25580042/7e24b8c5-aff3-463c-ac37-30aa3ed04033)

**Comment by MIDG3Tp3nguin** [comment]
> Just to clarify: I got the civitai extension working by changing the file `<my base directory>\stable-diffusion-webui\extensions\sd_civitai_extension\requirements.txt` from
> 
> ```
> python-socketio[client]==5.7.2
> ```
> 
> to
> 
> ```
> python-socketio[client]>=5.7.2
> ```
> 
> locally (Notice `>=` instead of `==`!). I have not experienced any bugs with the newer version, so I am staying on the version I am right now. This issues was raised as a feature request to incorporate my local change into future development for this extension, as I see no benefit in locking down the `python-socketion[client]` module to this exact version.

this removed the error for me
