### ISSUE TITLE
excute "python install.py", "ModuleNotFoundError: No module named 'launch'" happen

### ISSUE THREAD

**Issue by firebata** [civitai/sd_civitai_extension#51]
PS D:\stable-diffusion-webui\extensions> git clone git@github.com:civitai/sd_civitai_extension.git
Cloning into 'sd_civitai_extension'...
remote: Enumerating objects: 274, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (83/83), done.
Receiving objects: 100% (274/274), 69.99 KiB | 286.00 KiB/s, done.5

Resolving deltas: 100% (139/139), done.
PS D:\stable-diffusion-webui\extensions> dir

    目录: D:\stable-diffusion-webui\extensions

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/4/27     20:13                sd-webui-additional-networks
d-----         2023/4/27     20:22                sd_civitai_extension
d-----         2023/4/27     18:42                stable-diffusion-webui-chinese
-a----         2023/4/27     12:00              0 put extensions here.txt

PS D:\stable-diffusion-webui\extensions> cd .\sd_civitai_extension\
PS D:\stable-diffusion-webui\extensions\sd_civitai_extension> dir

    目录: D:\stable-diffusion-webui\extensions\sd_civitai_extension

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/4/27     20:22                civitai
d-----         2023/4/27     20:22                javascript
d-----         2023/4/27     20:22                scripts
-a----         2023/4/27     20:22            125 .gitignore
-a----         2023/4/27     20:22            257 DEVELOPING.md
-a----         2023/4/27     20:22           2709 install.py
-a----         2023/4/27     20:22            429 preload.py
-a----         2023/4/27     20:22           1857 README.md
-a----         2023/4/27     20:22             30 requirements.txt
-a----         2023/4/27     20:22           1594 style.css

PS D:\stable-diffusion-webui\extensions\sd_civitai_extension> python install.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd_civitai_extension\install.py", line 7, in <module>
    from launch import run
ModuleNotFoundError: No module named 'launch'
PS D:\stable-diffusion-webui\extensions\sd_civitai_extension>

**Comment by cikeaini** [comment]
same problem

**Comment by AbslanX** [comment]
same issue

**Comment by BinGoBinBin** [comment]
me too

**Comment by MIyulong** [comment]
i get those:
Traceback (most recent call last):
  File "/Users/xxx/Desktop/sd_civitai_extension/install.py", line 5, in <module>
    import git
ModuleNotFoundError: No module named 'git'

**Comment by CHNAICORP** [comment]
I found the issue. You need to install it from the "Install from URL" option in web-ui. If you installed it through "git clone https://github.com/civitai/sd_civitai_extension.git" method, running the "python install.py" command in the "extensions\sd_civitai_extension" directory will result in a "ModuleNotFoundError: No module named 'launch'" error.
![0208B8AD-9310-4e8b-83EB-ACC8E130F465](https://github.com/civitai/sd_civitai_extension/assets/61525966/682996e4-7ed3-4a06-b7df-b61007a7cb5f)
![65E7A9DD-806B-48d0-9D26-740869B685DD](https://github.com/civitai/sd_civitai_extension/assets/61525966/8ef0c9ca-bef7-4c54-b65c-19504d438e8c)
![5FDE8F0E-B827-49c5-BFD6-CF81E9734FCE](https://github.com/civitai/sd_civitai_extension/assets/61525966/f3543720-4901-4357-9551-74ec7cfb58dc)

**Comment by ekkirinaldi** [comment]
> i get those: Traceback (most recent call last): File "/Users/xxx/Desktop/sd_civitai_extension/install.py", line 5, in import git ModuleNotFoundError: No module named 'git'

you can go with:

`pip3 install gitpython` or `pip install gitpython`
