### ISSUE TITLE
what is the “civitai_link_key”？

### ISSUE THREAD

**Issue by chuju320** [civitai/sd_civitai_extension#55]
I found that the "civitai_link_key" is needed for sd_civitai_extension.So what is that?How can I get it?

**Comment by sadikh94** [comment]
Your civitai profile link. Сlick on your avatar, select "your profile" and then copy the link.

**Comment by chuju320** [comment]
I try this,but it does not work.The error steal appear:
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='civitai.com', port=80): Max retries exceeded with url: /api/v1/models?limit=50&types=Checkpoint&sort=Newest (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C1F9F7A5C0>, 'Connection to civitai.com timed out. (connect timeout=30)'))

**Comment by chuju320** [comment]
socketio.exceptions.ConnectionError: HTTPSConnectionPool(host='link.civitai.com', port=443): Max retries exceeded with url: /api/socketio/?transport=polling&EIO=4&t=1683113967.5443146 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000184105BD570>, 'Connection to link.civitai.com timed out. (connect timeout=5)'))

**Comment by fjh1997** [comment]
Also crash for me:
```
Civitai Link: Connecting to Civitai Link Server
Error executing callback app_started_callback for C:\stable-diffusion-webui\extensions\sd_civitai_extension\scripts\link.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 108, in app_started_callback
    c.callback(demo, app)
  File "C:\stable-diffusion-webui\extensions\sd_civitai_extension\scripts\link.py", line 13, in connect_to_civitai
    link.socketio_connect()
  File "C:\stable-diffusion-webui\extensions\sd_civitai_extension\civitai\link.py", line 201, in socketio_connect
    sio.connect(socketio_url, socketio_path='/api/socketio')
  File "C:\stable-diffusion-webui\venv\lib\site-packages\socketio\client.py", line 347, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
```

**Comment by fjh1997** [comment]
Finally,I make the connection work,but how about then? Seems nothing happend.I can't see any options added in the civitai.com website when exploring the model.
