### ISSUE TITLE
Error message since I upgraded to A1111 1.3.1

### ISSUE THREAD

**Issue by HeavyTony2** [civitai/sd_civitai_extension#74]
```
Exception in thread Thread-115 (load_previews):
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\anaconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd_civitai_extension\scripts\previews.py", line 16, in load_previews
    resources = civitai.load_resource_list()
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd_civitai_extension\civitai\lib.py", line 222, in load_resource_list
    resources += get_resources_in_folder('Checkpoint', shared.cmd_opts.ckpt_dir, ['safetensors', 'ckpt'], ['vae.safetensors', 'vae.ckpt'])
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\sd_civitai_extension\civitai\lib.py", line 176, in get_resources_in_folder
    os.makedirs(folder, exist_ok=True)
  File "C:\ProgramData\anaconda3\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\ProgramData\anaconda3\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by HeavyTony2** [comment]
Seems to be fixed
