### ISSUE TITLE
Failing to link to civitai with key (KeyError: 'content-length')

### ISSUE THREAD

**Issue by BlafKing** [civitai/sd_civitai_extension#84]
Hi all!
I'm trying to link my stable diffussion to civitai and it's giving out this error when I input a key:

```
changing setting civitai_link_key to 7b9de4: KeyError
Traceback (most recent call last):
  File "C:\Program Files\Automatic1111SD\webui\modules\shared.py", line 597, in set
    self.data_labels[key].onchange()
  File "C:\Program Files\Automatic1111SD\webui\extensions\sd_civitai_extension\civitai\link.py", line 230, in on_civitai_link_key_changed
    if not sio.connected: socketio_connect()
  File "C:\Program Files\Automatic1111SD\webui\extensions\sd_civitai_extension\civitai\link.py", line 217, in socketio_connect
    sio.connect(socketio_url, socketio_path='/api/socketio')
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\socketio\client.py", line 331, in connect
    self.eio.connect(real_url, headers=real_headers,
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\engineio\client.py", line 191, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\engineio\client.py", line 330, in _connect_polling
    if self._connect_websocket(url, headers, engineio_path):
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\engineio\client.py", line 433, in _connect_websocket
    ws = websocket.create_connection(
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\websocket\_core.py", line 608, in create_connection
    websock.connect(url, **options)
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\websocket\_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "C:\Program Files\Automatic1111SD\system\python\lib\site-packages\websocket\_handshake.py", line 147, in _get_resp_headers
    response_body = sock.recv(int(resp_headers['content-length']))  # read the body of the HTTP error message response and include it in the exception
KeyError: 'content-length'
```
Would love to know if there's anything I can try to make it work! :)

**Comment by kieranxsomer** [comment]
Same issue, Have told Maier about it: 
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/shared.py", line 597, in set
    self.data_labels[key].onchange()
  File "/workspace/stable-diffusion-webui/extensions/sd_civitai_extension/civitai/link.py", line 230, in on_civitai_link_key_changed
    if not sio.connected: socketio_connect()
  File "/workspace/stable-diffusion-webui/extensions/sd_civitai_extension/civitai/link.py", line 217, in socketio_connect
    sio.connect(socketio_url, socketio_path='/api/socketio')
  File "/workspace/venv/lib/python3.10/site-packages/socketio/client.py", line 331, in connect
    self.eio.connect(real_url, headers=real_headers,
  File "/workspace/venv/lib/python3.10/site-packages/engineio/client.py", line 191, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "/workspace/venv/lib/python3.10/site-packages/engineio/client.py", line 330, in _connect_polling
    if self._connect_websocket(url, headers, engineio_path):
  File "/workspace/venv/lib/python3.10/site-packages/engineio/client.py", line 433, in _connect_websocket
    ws = websocket.create_connection(
  File "/workspace/venv/lib/python3.10/site-packages/websocket/_core.py", line 608, in create_connection
    websock.connect(url, **options)
  File "/workspace/venv/lib/python3.10/site-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/workspace/venv/lib/python3.10/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/workspace/venv/lib/python3.10/site-packages/websocket/_handshake.py", line 147, in _get_resp_headers
    response_body = sock.recv(int(resp_headers['content-length']))  # read the body of the HTTP error message response and include it in the exception
KeyError: 'content-length'

This is WITH changing to a different API key.
:3

**Comment by Hezer** [comment]
I managed to fix this by updating websocket-client package from 1.5.2 => 1.5.3. There seems to be a bug on handling the "content-length" at least on that version of the package.

And here's a bit of guidance for how to do the update on your environment. First open a command prompt / terminal on "stable-diffusion-webui" folder. The folder should have a `venv` folder in it for the rest of the instructions to work on your environment. If you have the virtual environment in a different folder, adjust the commands for it where venv is mentioned.

If on windows you can do command: `cd <path-to-folder>` for example `cd C:\StableDiffusion A1111-WebUI\stable-diffusion-webui` and if your webui is on a different drive, you can do just `D:` before the `cd` command.

1. Activate the virtual environment for webui.
`.\venv\Scripts\activate`

2. Check the version of websocket-client package. My version was 1.5.2 and this seemed to have a bug in handling the "content-length" header.
`python -m pip show websocket-client`

3. Update the package to 1.5.3.
`python -m pip install websocket-client==1.5.3`

4. Finally, close the command line window or run `deactivate` command to close the virtual environment.

Kudos to `@chekaa` on Civitai discord for figuring out the problem and pointing me at the right direction. All I needed to do then was to check, if there was a package version where the bug was fixed.

**Comment by tombon12** [comment]
> I managed to fix this by updating websocket-client package from 1.5.2 => 1.5.3. There seems to be a bug on handling the "content-length" at least on that version of the package.
> 
> And here's a bit of guidance for how to do the update on your environment. First open a command prompt / terminal on "stable-diffusion-webui" folder. The folder should have a `venv` folder in it for the rest of the instructions to work on your environment. If you have the virtual environment in a different folder, adjust the commands for it where venv is mentioned.
> 
> If on windows you can do command: `cd <path-to-folder>` for example `cd C:\StableDiffusion A1111-WebUI\stable-diffusion-webui` and if your webui is on a different drive, you can do just `D:` before the `cd` command.
> 
> 1. Activate the virtual environment for webui.
>    `.\venv\Scripts\activate`
> 2. Check the version of websocket-client package. My version was 1.5.2 and this seemed to have a bug in handling the "content-length" header.
>    `python -m pip show websocket-client`
> 3. Update the package to 1.5.3.
>    `python -m pip install websocket-client==1.5.3`
> 4. Finally, close the command line window or run `deactivate` command to close the virtual environment.
> 
> Kudos to `@chekaa` on Civitai discord for figuring out the problem and pointing me at the right direction. All I needed to do then was to check, if there was a package version where the bug was fixed.

That has worked wonders!
I couldn't really manage to get make the command  `python -m pip install websocket-client==1.5.3` install at the same location which Automatic1111 uses being: `MAIN\system\python\Lib\site-packages`.
I just removed the websocket & websocket_client-1.5.2.dist-info from this directory and manually replaced them with the new websocket & websocket_client-1.5.3.dist-info files which has fixed it!

thx for the great guide on how to fix the issue! :)

**Comment by Hubert200704** [comment]
I'm also working on this SD Civitia Helper and met the same problem. But after trying the latest(1.7.0) & 1.5.3 of websocket-client, the problem reoccurs. I would really appreciate it if you guys spare sometime to take a look. I'm thinking it might be something about my proxy?

> Civitai Helper: Start downloading from: https://civitai.com/api/download/models/372799
Traceback (most recent call last):
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Programming\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 105, in dl_model_by_input
    return model_action_civitai.dl_model_by_input(dl_model_info, dl_model_type_txtbox, dl_subfolder_drop, dl_version_drop, dl_all_ckb, max_size_preview, skip_nsfw_preview)
  File "D:\Programming\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 484, in dl_model_by_input
    filepath = downloader.dl(url, model_folder, None, None)
  File "D:\Programming\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\downloader.py", line 37, in dl
    total_size = int(rh.headers['Content-Length'])
  File "D:\Programming\stable-diffusion-webui\venv\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
